name: Python application test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test_api_login:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.12.1' ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout external repository
        uses: actions/checkout@v4
        with:
          repository: "slawekradzyminski/awesome-localstack"
          path: "awesome-localstack"

      - name: Run Docker Compose
        run: |
          cd awesome-localstack
          chmod +x run-docker-compose-ci.sh
          ./run-docker-compose-ci.sh

      - name: Installing all necessary packages
        run: pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
          echo "BACKEND_URL=${{ secrets.BACKEND_URL }}" >> .env
          echo "ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}" >> .env
          echo "ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}" >> .env
          echo "IS_HEADLESS=${{ secrets.IS_HEADLESS }}" >> .env

      - name: API tests
        env:
          BACKEND_URL: "http://localhost:4001"
        run: pytest tests/api/test_api_login.py